# NEMA flood risk
<!-- markdownlint-disable MD013 -->

In [1]:
%load_ext jupyter_black
%load_ext autoreload
%autoreload 2

In [9]:
from src.datasources import codab
from src.utils import blob
from src.constants import *

In [7]:
adm2 = codab.load_codab_from_blob(aoi_only=True, admin_level=2)

In [8]:
adm2

,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,ADM0_EN,ADM0_PCODE,DATE,VALIDON,VALIDTO,geometry
2,Abadam,NG008001,Borno,NG008,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((13.11029 13.10963, 13.10815 13.11404..."
68,Askira/Uba,NG008002,Borno,NG008,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((13.09852 10.44508, 13.09352 10.44667..."
82,Bade,NG036001,Yobe,NG036,Nigeria,NG,2017-03-31,2019-04-17,None,"MULTIPOLYGON (((11.18769 12.50815, 11.18360 12..."
90,Bama,NG008003,Borno,NG008,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((13.99056 11.31251, 13.97581 11.30513..."
99,Bayo,NG008004,Borno,NG008,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((11.65688 10.19681, 11.60128 10.20806..."
...,...,...,...,...,...,...,...,...,...,...
709,Toungo,NG002019,Adamawa,NG002,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.21046 7.97042, 12.20300 7.96432, ..."
762,Yola North,NG002020,Adamawa,NG002,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.40447 9.25767, 12.40226 9.26307, ..."
763,Yola South,NG002021,Adamawa,NG002,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.43708 9.21300, 12.43732 9.21285, ..."
765,Yunusari,NG036016,Yobe,NG036,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.13949 13.09935, 12.14254 13.09896..."
766,Yusufari,NG036017,Yobe,NG036,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((11.32417 13.15145, 11.32829 13.14117..."

In [3]:
blob_name = f"{blob.PROJECT_PREFIX}/raw/AA-nigeria_data/NEMA/Flood Risk Excel Data 2.xlsx"

In [4]:
df = blob.load_excel_from_blob(blob_name)

In [10]:
df = df[df["ADM1_PCODE"].isin(AOI_ADM1_PCODES)]

In [17]:
df["Riverine Flood Risk"].value_counts()

Riverine Flood Risk
High      19
Medium    14
Low        6
Name: count, dtype: int64

In [18]:
df["Flash Flood Risk"].value_counts()

Flash Flood Risk
High      29
Medium    17
Low       14
Name: count, dtype: int64

In [19]:
df["Coastal Flood Risk"].value_counts()

Series([], Name: count, dtype: int64)

In [20]:
df.merge(adm2)

,ADM2_EN,ADM2_PCODE,ADM1_EN,ADM1_PCODE,STATE,ADM2_PCODE2,Riverine Flood Risk,Flash Flood Risk,Coastal Flood Risk,Comments,Column3,ADM0_EN,ADM0_PCODE,DATE,VALIDON,VALIDTO,geometry
0,Abadam,NG008001,Borno,NG008,Borno,NG008001,Low,Low,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((13.11029 13.10963, 13.10815 13.11404..."
1,Askira/Uba,NG008002,Borno,NG008,Borno,NG008002,Medium,Low,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((13.09852 10.44508, 13.09352 10.44667..."
2,Bade,NG036001,Yobe,NG036,Yobe,NG036001,High,High,NaN,PREVALENCE OF RIVERINE FLOOD IS MORE,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"MULTIPOLYGON (((11.18769 12.50815, 11.18360 12..."
3,Bama,NG008003,Borno,NG008,Borno,NG008003,Medium,Medium,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((13.99056 11.31251, 13.97581 11.30513..."
4,Bayo,NG008004,Borno,NG008,Borno,NG008004,NaN,High,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((11.65688 10.19681, 11.60128 10.20806..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Toungo,NG002019,Adamawa,NG002,Adamawa,NG002019,NaN,NaN,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.21046 7.97042, 12.20300 7.96432, ..."
61,Yola North,NG002020,Adamawa,NG002,Adamawa,NG002020,High,High,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.40447 9.25767, 12.40226 9.26307, ..."
62,Yola South,NG002021,Adamawa,NG002,Adamawa,NG002021,High,High,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.43708 9.21300, 12.43732 9.21285, ..."
63,Yunusari,NG036016,Yobe,NG036,Yobe,NG036016,NaN,Medium,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((12.13949 13.09935, 12.14254 13.09896..."
64,Yusufari,NG036017,Yobe,NG036,Yobe,NG036017,NaN,Low,NaN,<Null>,NaN,Nigeria,NG,2017-03-31,2019-04-17,None,"POLYGON ((11.32417 13.15145, 11.32829 13.14117..."